version: "3"

services:

  ckan:
    image: ckan_ckan:base
    container_name: ckan-base
    build:
      context: ckan/
      dockerfile: Dockerfile
      args:
        - TZ=${TZ}
    env_file:
      - .env
    environment:
      - CKAN__PLUGINS=envvars image_view text_view recline_view datastore datapusher
      - CKAN__VIEWS__DEFAULT_VIEWS=image_view text_view recline_view
      - CKAN__FAVICON=https://www.estar.toscana.it/wp-content/uploads/2021/04/Logo-Estar_150x150.png
    links:
      - db
      - solr
      - redis
      - datapusher
    ports:
      - "0.0.0.0:${CKAN_PORT}:5000"
    volumes:
      - ckan_storage:/var/lib/ckan

  datapusher:
    image: ckan_datapusher:base
    container_name: datapusher-base
    build:
      context: datapusher/

  db:
    image: ckan_db:base
    container_name: db-base
    build:
      context: postgresql/
      args:
        - DATASTORE_READONLY_PASSWORD=${DATASTORE_READONLY_PASSWORD}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    environment:
      - DATASTORE_READONLY_PASSWORD=${DATASTORE_READONLY_PASSWORD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/db
    volumes:
      - pg_data:/var/lib/postgresql/data

  solr:
    image: ckan/ckan-solr:2.9-solr8
    container_name: solr-base
    volumes:
      - solr_data:/opt/solr/server/solr/ckan/data/index

  redis:
    container_name: redis-base
    image: redis:7-alpine

volumes:
  ckan_storage:
  pg_data:
  solr_data:
