version: '3'

services:

  solr:
    image: solr:8
    ports:
      - "8983:8983"
    command:
      - solr-precreate
      - reuters

  app:
    build: .
    environment:
      - SOLR_HOST=solr
    ports:
      - 5000:5000
