version: '3'

services:

  db:
    image: postgis/postgis:14-3.3-alpine
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432

  adminer:
    image: adminer:4
    ports:
      - "8080:8080"

  app:
    build: .
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=db
      - DB_NAME=postgres
    ports:
      - "5000:5000"
